language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: d3IRhxZYHkOHkAERn/1KCiHgybrlJH3QI5zTafxqMXa/jQ4eVjCEk/3GHDP97QhjG4wDD/+0DzrKvxxXWS8HJFKMGjhq82qhkQSxBQvaR1D184ZNdlCntT3R4B4YjRQJQV4zJjj2DeGHrgoUNaODUGOzsaollmWKqbe19ULaURga3eEaIxM/QWwowcWsJXQMLdgxUC/AkPlwmjZrezGc/3jZreWtCxg98JzkN4zrMzFsIUINB8ABteBlyc+dpclGkjW8gSOFi/2b56lMk//es24ldjhQ1wSNprSx8aTNgkYC3Pd6ZZsjFSRzTWaKIZOyKOv92ZCN99ORWd9AymkhE1tXAFO1Or47KmrKOddx7sMCHRZYcL06oknk+NC7qSpYFxOFGxdjW363WWni2RMHR1XhfRRBlU3pc5eBTiq1s8idbuNvxs28QEKe6VzyM6UB6/ce89qEzlC2ZCJ9PKBYZW8HtzTUZ2SZBMCQ8Y6tGqpYJGuVK+VyB50Y8gjQxvjXbJmnsL7thauY6+faBRq6MYnfsVW4lT+/xMb7gFlbDinaPc5kGx29YM4fU2UX8qQKPfQKAN+0M7hlNRHSHPj7dfyWJ7it9hLJVJ11wUaIR/hIHeJa+nFKJ8GtoV2H70zZki89VobtI25RABEetDdJYVfLKvyCrD8HNX4c7iHQIXE=
  app: lit-journey-4733
  on:
    repo: KahokuHanten/oyako
  run:
  - rake db:migrate
  - rake db:seed
cache:
  directories:
  - vendor/bundle
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
notifications:
  slack:
    secure: rgIOezoWFKVy6FE0wPUX4g/eapyoEb3OfVJCYrhvcfjX5WqEuIFaomYEk7rOiqRP8uy0YIXsQWswBgaiiAKhTZBN779ztGDjAX8f+ikior37XKPhq8CPGALtmVmeIIzf61UlrEzVKEFGkIRoWg02iieazij73074qaJbjlppbnjs54cgYFovcZM9sd3mfzvpJpEp0zkZGgc7ULlgHTOp2kDlo54J2lhFaf7pXoClk2ujgYbtMJ1ozcktE/gl3jDWLXoUlvRpHVvMnye71x8dqSP9NcY6HZ9kywyT0FleWNFAZJHGhZj9ffv2rtKMX09JP45chQBiteF9F3150eZu7N5tWxxrAqQam6e9zxNczoD9TB7hQvYNfXlC6Bg1wS8QqL+BMzRPqN+lRHZrzdXJTGIdaybEKwyUIG/V0GbLEIDqMx6JewY4haY55/w0bECU1Pjv4fdG4ke8DiNDX4JnMlLKBj92a4uJKV9YAVdH/887ox98N6G7kHQwpT0Njf/9/Haib2F62IAuY0RSTmGobfEz68+XqoxdVBx/kOvUSmZr5HLONbLrrd/fwljHYzTSYYrqBIn4Lh246ljg6F8OfzR8ik24LrU45S6I68Aylet87uZ2VRtw4PTkoNjs+J6rzBkhRcl+gD3DAONIJEQxc0mcjTKyJK7ldVsPyqTuWso=
env:
  global:
    - secure: "tYjOq29gGsZGoGCGVbpse8YrqJwcvYyptRCxOqDipNZ4v/jQ9/PAZmYueK6KhG9PkAiehYgxqMSLPkZjv00Po65EqiQeDo/1hDEdFb03ZYCGO0U8h/gLZUolqOAkbLGMjp99KH8j9YPvuydPNFYSrdZ5cESYceXqPTAxnNfbH4aL2XPmGf862aHL9cAft1qn5wAv3dRZsYOJXMNiPsZ4J8VsYwzFfYoogq6/IUZpqNV+q0nQwfIxnHKHHu0vuFcHOrbOrEfzax6HihMZeGlMDlAJm4X56d1U5E6pKlbIRokiSRtQejJIOneQRd5YMvekHRm7fIEkWuIYNYWiKd5HG7X/0V2YQw0WsertpM6Pbqjo5gl29sMjXu3G6jYZz0QOw1T8Eagv+XXnLXS+Zhxiio7k4chGlD/8yCPn+ZW5nk8ltzztMxfqCYCrRzsRCzmXkMcTAiEDGlibEJbvAzAXy6j1TMC5lfp4scBEMPfErxSsY5aHrlIpZRhjqus3zJdXfhR3f18zp+3niLy9hhraWTWKee/VZLIXvBernPKp3aHweG2m1krPptGDDm8u3jfcPDZzNZ/fIc7iaXQAdGBOMOkoaFtDi2ERp5CH2Xc0b6zqlOfrp9PBn6j6dSYUQPq2c623xu7nS51PRwNOdd/M6Wt2dqd9JA6PH5kSuEohkkM="
    - secure: "jahCN7FycQu5W+9aUVa2lCjrKxzACAYawCnOLr6jZ/8ikwFvbl5wAZbFE3TwUaInbNrcEfj+fJyuHX91PRK1YNo0SYBus3hUcRSOn6ZjSupXEJ5eZNeQgzCPPLAEgvfXWeyS1+kb/kdwOBunE9IkOMFhD99PO8Bmg+VTmWkybpfBfom6v0bj1OQbfWtYXGkbXYtk0ITjMRcFqyhNfFaujVY5KnS65S6PdSnXRkPTo1E3dGsWq0XBDlW/bJXu59cwIhq5h5GJF69iID2u07rgKGlS/GIcMF8esDIS6UCYxT004BwtWKSCqpY2+i4Sw0kwUehL0qEhDnNqM5QoV9H+ey5lf0mY8YRrGz/n0ozYXJuNWzI7n9z3adP71vSAmWBTfJ8zjVuGFBruR92/R8BPN8ZIjYwymjoiPGIFNim5tzSx2NRb9COAVwZadbPSQnz2Xe0IgbHi5kM0pghljyQ4xyIJIFE1LKDujmzk2b77gShdwQVXLa5ubfxfYmodrzHckZA++lpUtVCLnJtk/sffuiMfrtfLe1Hh9l1lTFSchek01K8X0vFcG+U3RiHBUPkKVw9HUh7lgpjfWmr1JAD3E+fC2XnNwujxQVGpmdXsQIHOg11T4xKXtwBM30DpRAPzw4fwKGAvTfCOGQGhLIE3R7OByOfmA5eoLSre4BuJ6Vk="