language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: d3IRhxZYHkOHkAERn/1KCiHgybrlJH3QI5zTafxqMXa/jQ4eVjCEk/3GHDP97QhjG4wDD/+0DzrKvxxXWS8HJFKMGjhq82qhkQSxBQvaR1D184ZNdlCntT3R4B4YjRQJQV4zJjj2DeGHrgoUNaODUGOzsaollmWKqbe19ULaURga3eEaIxM/QWwowcWsJXQMLdgxUC/AkPlwmjZrezGc/3jZreWtCxg98JzkN4zrMzFsIUINB8ABteBlyc+dpclGkjW8gSOFi/2b56lMk//es24ldjhQ1wSNprSx8aTNgkYC3Pd6ZZsjFSRzTWaKIZOyKOv92ZCN99ORWd9AymkhE1tXAFO1Or47KmrKOddx7sMCHRZYcL06oknk+NC7qSpYFxOFGxdjW363WWni2RMHR1XhfRRBlU3pc5eBTiq1s8idbuNvxs28QEKe6VzyM6UB6/ce89qEzlC2ZCJ9PKBYZW8HtzTUZ2SZBMCQ8Y6tGqpYJGuVK+VyB50Y8gjQxvjXbJmnsL7thauY6+faBRq6MYnfsVW4lT+/xMb7gFlbDinaPc5kGx29YM4fU2UX8qQKPfQKAN+0M7hlNRHSHPj7dfyWJ7it9hLJVJ11wUaIR/hIHeJa+nFKJ8GtoV2H70zZki89VobtI25RABEetDdJYVfLKvyCrD8HNX4c7iHQIXE=
  app: lit-journey-4733
  on:
    repo: KahokuHanten/oyako
  run:
  - rake db:migrate
  - rake db:seed
cache:
  directories:
  - vendor/bundle
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
env:
  secure: X06uVNap1PNTVgEx6SIKPUHbgOEk313WqtU43R+O57hoR43DtGNYf8RkqNXa37ikQAbYknbNbdKqmAUyDBMpFw9DhreaMc/xg9rg8xCwOT2v1MZ2VN4sB7J6wGSd66El61Qc+VBM/uw0PJpWO3hqnDrdIO8BS1XdqxtVih7BAMdn0rw7q6B3V901wzPaizctzGdX8f9DZIyF2VUAIP4SCrYm+39ZiKbx39IwNG7KDYT2vnQr8pICXc2v7tVhqtlqM2oSDWiuhY6yI4HnFjNgZYEPCqCoFqdw0aV6MckGg7YF7qojO1idqFFKBPw9r/nC0XssSjs4FEYEb0qncJTBWCJuM3qgCVGR2gl+T47wDpBDwEnqbJ+z94QPFNRN126Q0VUMFLiJeSXLrwsD2oDN2QCxTjGIMKXIRaVoA5yCZx2ytQgvHwBieIHzzCIjw/sWx3OEnd7sPACgNZY/EmF973W1wKqJPvDAioVCZ+REMgDjHgmI8oFe+fp41XD2CKq5eXc4/vxFfymr+65jgbRgPma+AF7R9UyO2ecvdtkxDd0hPhL6qcOfQHz4bOojXSFaYeR1JExyXe6BCMcM3uCsDdWLhgXSZOHl9VP7M7pQsHFyJA+f3+QHXz6t9AjbkbxvGYvhIGMb4NJy+WUwBhNmm/QTkWSqWM+W7aoD/Qy45nc=
